# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70c196b50edac476f69c187a486f1c6c357f50a988e276afd280bf4b0c3cc332863bc37e21673fe9ede81a7d7038a015c6bfeb2298c4a82129d5ef52c4fce1f5

test:
  secret_key_base: 34b8da200c8a813cdf28270768276615d46e2ae0fd6093d1b8bdc4653f6f5a54e26107a476a1f3ff94cf50218ceffbb7d4b3bfbb1d0b80fa58bec71d9d6fcc68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
